---
version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
    volumes:
      - /media/data/docker/plex:/config
      - /media/data/media/:/media
    restart: unless-stopped
  
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/pi/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      # qbittorrent
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      # radarr
      - 7878:7878
      # prowlarr
      - 9696:9696
      # sonarr
      - 8989:8989
      # lidarr
      - 8686:8686
      # readarr
      - 8787:8787
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /media/data/docker/qbittorrent:/config
      - /media/data/media:/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/data/docker/radarr:/config
      - /media/data/media:/media
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/data/docker/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/data/docker/sonarr:/config
      - /media/data/media:/media
    restart: unless-stopped
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/data/docker/lidarr:/config
      - /media/data/media:/media
    restart: unless-stopped
  
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/data/docker/readarr:/config
      - /media/data/media:/media
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=America/New_York
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /media/data/docker/watchtower:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /media/data/docker/code-server:/config
      - /media/data/projects:/projects
    ports:
      - 8443:8443
    restart: unless-stopped

  # nextcloud:
  #   image: lscr.io/linuxserver/nextcloud:latest
  #   container_name: nextcloud
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /media/data/docker/nextcloud:/config
  #     - /media/data/media/nextcloud:/data
  #   ports:
  #     - 443:443
  #   restart: unless-stopped
